---
- name: Install Grafana
  hosts: vlogs-bench 
  become: yes
  vars:
    victorialogs_datasource_version: 0.2.3
  
  tasks:
    - name: Install required packages 
      apt:
        name: "{{ item }}"
        state: present
      loop:
        - adduser
        - libfontconfig1

    - name: Download Grafana deb package
      get_url:
        url: https://dl.grafana.com/oss/release/grafana_10.0.3_amd64.deb
        dest: /tmp/grafana_10.0.3_amd64.deb

    - name: Install Grafana deb package
      apt:
        deb: /tmp/grafana_10.0.3_amd64.deb
        state: present
      
    - name: Grafana configuration file
      template:
        src: templates/grafana-config.j2
        dest: /etc/grafana/grafana.ini

    
    - name: Ensure plugins directory exists
      file:
        path: /var/lib/grafana/plugins
        state: directory
  
    - name: Download victorialogs-datasource plugin tarball
      get_url:
        url: "https://github.com/VictoriaMetrics/victorialogs-datasource/releases/download/v{{ victorialogs_datasource_version }}/victorialogs-datasource-v{{ victorialogs_datasource_version }}.tar.gz"
        dest: "/etc/grafana/plugins/victorialogs-datasource-v{{ victorialogs_datasource_version }}.tar.gz"

    - name: Extract victorialogs-datasource plugin
      unarchive:
        src: "/etc/grafana/plugins/victorialogs-datasource-v{{ victorialogs_datasource_version }}.tar.gz"
        dest: "/var/lib/grafana/plugins"
        remote_src: yes
        creates: "/var/lib/grafana/plugins/victorialogs-datasource"
    
    - name: Restart Grafana service
      service:
        name: grafana-server
        state: restarted
        enabled: yes