---
- name: Install Netdata On-Prem Version
  hosts: all
  become: yes
  tasks:
    - name: Install wget
      apt:
        name: wget
        state: present
        update_cache: yes

    - name: Download Netdata kickstart script
      get_url:
        url: https://get.netdata.cloud/kickstart.sh
        dest: /tmp/netdata-kickstart.sh
        mode: '0755'

    - name: Prepare for offline install
      shell: sh /tmp/netdata-kickstart.sh --prepare-offline-install-source /tmp/netdata-offline
      args:
        creates: /tmp/netdata-offline

    - name: Install Netdata from offline source
      shell: sh /tmp/netdata-offline/netdata-installer.sh --dont-wait

    - name: Enable and start Netdata service
      systemd:
        name: netdata
        enabled: yes
        state: started

    - name: Allow Netdata default port through the firewall
      ufw:
        rule: allow
        port: 19999
        proto: tcp
        state: enabled
        name: 'Netdata'
      when: ansible_facts['os_family'] == "Debian"  # Ensure UFW is used only on Debian-based systems