---
- name: Setup Victorialogs service
  hosts: vlogs-bench
  become: true
  vars:
    victorialogs_group: victoriametrics
    victorialogs_user: victoriametrics
    victorialogs_version: 0.25.0
    victorialogs_install_dir: /usr/local/bin/
    victorialogs_service_file: /etc/systemd/system/victorialogs.service
    victorialogs_storage_path: /mnt/logs/
    
  tasks:
    - name: Create victorialogs group
      group:
        name: "{{ victorialogs_group }}"
        system: yes

    - name: Create victorialogs user
      user:
        name: "{{ victorialogs_user }}"
        system: yes
        group: "{{ victorialogs_group }}"
        home: /nonexistent
        shell: /bin/false
        create_home: no

    - name: Download victoria-logs tar.gz
      get_url:
        url: "https://github.com/VictoriaMetrics/VictoriaMetrics/releases/download/v{{ victorialogs_version }}-victorialogs/victoria-logs-linux-amd64-v{{ victorialogs_version }}-victorialogs.tar.gz"
        dest: "/tmp/victoria-logs-linux-amd64-v{{ victorialogs_version }}-victorialogs.tar.gz"

    - name: Extract victoria-logs tar.gz
      unarchive:
        src: "/tmp/victoria-logs-linux-amd64-v{{ victorialogs_version }}-victorialogs.tar.gz"
        dest: "{{ victorialogs_install_dir }}"
        remote_src: yes

    - name: Ensure victoria-logs binary is executable
      file:
        path: "{{ victorialogs_install_dir }}"
        mode: '0755'

    - name: Create victorialogs service file from template
      template:
        src: templates/vlogs-systemd.j2
        dest: "{{ victorialogs_service_file }}"

    - name: Reload systemd daemon
      systemd:
        daemon_reload: yes

    - name: Start victorialogs service
      service:
        name: victorialogs
        state: started

    - name: Enable victorialogs service
      service:
        name: victorialogs
        enabled: yes
    
    - name: Change ownership of log storage
      become: yes
      become_user: root
      command: chown -R {{ victorialogs_user }}:{{ victorialogs_group }} {{ victorialogs_storage_path }}

  handlers:
    - name: restart victorialogs
      service:
        name: victorialogs
        state: restarted
        enabled: yes